// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SoccerOpenServer.Migrations
{
    [DbContext(typeof(SoccerDbContext))]
    [Migration("20260920152526_AddTrainingSchedules")]
    partial class AddTrainingSchedules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<Guid>("CompetitionsCompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamsTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetitionsCompetitionID", "TeamsTeamID");

                    b.HasIndex("TeamsTeamID");

                    b.ToTable("CompetitionTeam");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.Competition", b =>
                {
                    b.Property<Guid>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompetitionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompetitionTeamsType")
                        .HasColumnType("int");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ContinentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("ServerID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompetitionID");

                    b.HasIndex("ContinentID");

                    b.HasIndex("NationID");

                    b.HasIndex("ServerID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.CompetitionTable", b =>
                {
                    b.Property<Guid>("CompetitionTableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("CompetitionTableID");

                    b.ToTable("CompetitionTables");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.CupRound", b =>
                {
                    b.Property<Guid>("CupRoundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("RoundType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamCount")
                        .HasColumnType("int");

                    b.HasKey("CupRoundID");

                    b.HasIndex("CompetitionID", "RoundNumber")
                        .IsUnique();

                    b.ToTable("CupRounds");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.CupTie", b =>
                {
                    b.Property<Guid>("CupTieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AdvancesAsHomeTeam")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AwayTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CupRoundID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HomeTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NextCupTieID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TieNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("WinnerTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CupTieID");

                    b.HasIndex("NextCupTieID");

                    b.HasIndex("CupRoundID", "TieNumber")
                        .IsUnique();

                    b.ToTable("CupTies");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Contracts.Contract", b =>
                {
                    b.Property<Guid>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<byte?>("ShirtNumber")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Wage")
                        .HasColumnType("int");

                    b.HasKey("ContractID");

                    b.HasIndex("PersonID");

                    b.HasIndex("TeamID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.CoachStats", b =>
                {
                    b.Property<Guid>("CoachStatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Attack")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Control")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Defend")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Fitness")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Goalkeeper")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Tactic")
                        .HasColumnType("tinyint");

                    b.HasKey("CoachStatsID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("CoachStats", t =>
                        {
                            t.HasCheckConstraint("CK_CoachStats_Attack", "[Attack] >= 1 AND [Attack] <= 100");

                            t.HasCheckConstraint("CK_CoachStats_Control", "[Control] >= 1 AND [Control] <= 100");

                            t.HasCheckConstraint("CK_CoachStats_Defend", "[Defend] >= 1 AND [Defend] <= 100");

                            t.HasCheckConstraint("CK_CoachStats_Fitness", "[Fitness] >= 1 AND [Fitness] <= 100");

                            t.HasCheckConstraint("CK_CoachStats_Goalkeeper", "[Goalkeeper] >= 1 AND [Goalkeeper] <= 100");

                            t.HasCheckConstraint("CK_CoachStats_Tactic", "[Tactic] >= 1 AND [Tactic] <= 100");
                        });
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.ManagerFormationPicked", b =>
                {
                    b.Property<Guid>("ManagerFormationPickedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Formation")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimesPicked")
                        .HasColumnType("int");

                    b.HasKey("ManagerFormationPickedID");

                    b.HasIndex("PersonID", "Formation")
                        .IsUnique();

                    b.ToTable("ManagerFormationPickedTable");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.ManagerGameStats", b =>
                {
                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CupsWon")
                        .HasColumnType("int");

                    b.Property<int>("Draws")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("LeaguesWon")
                        .HasColumnType("int");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("PersonID");

                    b.ToTable("ManagerGameStatsTable");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.MedicStats", b =>
                {
                    b.Property<Guid>("MedicStatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Diagnosis")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Prevention")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Rehabilitation")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Treatment")
                        .HasColumnType("tinyint");

                    b.HasKey("MedicStatsID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("MedicStats", t =>
                        {
                            t.HasCheckConstraint("CK_MedicStats_Diagnosis", "[Diagnosis] >= 1 AND [Diagnosis] <= 100");

                            t.HasCheckConstraint("CK_MedicStats_Prevention", "[Prevention] >= 1 AND [Prevention] <= 100");

                            t.HasCheckConstraint("CK_MedicStats_Rehabilitation", "[Rehabilitation] >= 1 AND [Rehabilitation] <= 100");

                            t.HasCheckConstraint("CK_MedicStats_Treatment", "[Treatment] >= 1 AND [Treatment] <= 100");
                        });
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ServerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StaffRole")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TrainingScheduleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("PersonID");

                    b.HasIndex("NationID");

                    b.HasIndex("ServerID");

                    b.HasIndex("TrainingScheduleID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PersonHealthAndFitness", b =>
                {
                    b.Property<Guid>("PersonHealthAndFitnessID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("FitnessCondition")
                        .HasColumnType("tinyint");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<byte>("MentalCondition")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("PhysicalCondition")
                        .HasColumnType("tinyint");

                    b.HasKey("PersonHealthAndFitnessID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("PersonHealthAndFitnesses");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerCompetitionDiscipline", b =>
                {
                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("PersonID", "CompetitionID");

                    b.HasIndex("CompetitionID");

                    b.ToTable("PlayerCompetitionDisciplines", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerCompetitionDiscipline_YellowCards", "[YellowCards] >= 0 AND [YellowCards] < 3");
                        });
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerStats", b =>
                {
                    b.Property<Guid>("PlayerStatsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Acceleration")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Control")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Creativity")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Crossing")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Decisions")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Dribbling")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Goalkeeping")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Jumping")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Kicking")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Passing")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Positioning")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Shooting")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Speed")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Stamina")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Strength")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Tackling")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Teamwork")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerStatsID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.Property<Guid>("PlayerTrainedPositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<byte>("PlayerTrainedPositionAdaptation")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerTrainedPositionID");

                    b.HasIndex("PersonID");

                    b.ToTable("PlayerTrainedPositions");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.Property<Guid>("PlayerTrainedRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<byte>("PlayerTrainedRoleAdaptation")
                        .HasColumnType("tinyint");

                    b.HasKey("PlayerTrainedRoleID");

                    b.HasIndex("PersonID");

                    b.ToTable("PlayerTrainedRoles");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerUnavailability", b =>
                {
                    b.Property<Guid>("PlayerUnavailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompetitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MatchesRemaining")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PlayerUnavailabilityID");

                    b.HasIndex("CompetitionID");

                    b.HasIndex("PersonID");

                    b.ToTable("PlayerUnavailabilities", t =>
                        {
                            t.HasCheckConstraint("CK_PlayerUnavailability_MatchesRemaining", "[MatchesRemaining] > 0");
                        });
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Servers.Server", b =>
                {
                    b.Property<Guid>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.HasKey("ServerID");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Kit", b =>
                {
                    b.Property<Guid>("KitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AwayShirtColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwayShortsColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeShirtColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeShortsColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KitShape")
                        .HasColumnType("int");

                    b.HasKey("KitID");

                    b.ToTable("Kits");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.PlayerTactic", b =>
                {
                    b.Property<Guid>("PlayerTacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlayerPosition")
                        .HasColumnType("int");

                    b.Property<int>("PlayerRole")
                        .HasColumnType("int");

                    b.Property<int>("SquadUnit")
                        .HasColumnType("int");

                    b.Property<int?>("SubstituteOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("TacticID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayerTacticID");

                    b.HasIndex("PersonID");

                    b.ToTable("PlayerTactics");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Stadium", b =>
                {
                    b.Property<Guid>("StadiumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StadiumState")
                        .HasColumnType("int");

                    b.HasKey("StadiumID");

                    b.ToTable("Stadium");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Tactic", b =>
                {
                    b.Property<Guid>("TacticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AttackLeft")
                        .HasColumnType("bit");

                    b.Property<bool>("AttackMiddle")
                        .HasColumnType("bit");

                    b.Property<bool>("AttackRight")
                        .HasColumnType("bit");

                    b.Property<bool>("EarlyCrosses")
                        .HasColumnType("bit");

                    b.Property<int>("Formation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("OffsideTrap")
                        .HasColumnType("bit");

                    b.Property<int>("PassingMentality")
                        .HasColumnType("int");

                    b.Property<int>("TacticMentality")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isMain")
                        .HasColumnType("bit");

                    b.HasKey("TacticID");

                    b.HasIndex("TeamID");

                    b.ToTable("Tactics");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.Property<Guid>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BadgePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KitID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StadiumID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamID");

                    b.HasIndex("AppUserID")
                        .IsUnique()
                        .HasFilter("[AppUserID] IS NOT NULL");

                    b.HasIndex("KitID")
                        .IsUnique();

                    b.HasIndex("StadiumID")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.TeamTacticPriority", b =>
                {
                    b.Property<Guid>("TeamTacticPriorityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TeamTacticPriorityID");

                    b.HasIndex("PersonID");

                    b.HasIndex("TeamID", "Type", "PersonID")
                        .IsUnique();

                    b.HasIndex("TeamID", "Type", "Priority")
                        .IsUnique();

                    b.ToTable("TeamTacticPriorities", t =>
                        {
                            t.HasCheckConstraint("CK_TeamTacticPriority_Priority", "[Priority] >= 1");
                        });
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Training.TrainingSchedule", b =>
                {
                    b.Property<Guid>("TrainingScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AttackPoints")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("CoachID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ControlPoints")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DefendPoints")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FitnessPoints")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GoalkeeperPoints")
                        .HasColumnType("tinyint");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TacticPoints")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("TeamID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrainingScheduleLevel")
                        .HasColumnType("int");

                    b.HasKey("TrainingScheduleID");

                    b.ToTable("TrainingSchedule");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid?>("PersonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("PersonID")
                        .IsUnique()
                        .HasFilter("[PersonID] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUserClaim", b =>
                {
                    b.Property<Guid>("AppUserClaimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AppUserClaimID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefreshTokenID");

                    b.HasIndex("AppUserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.World.Continent", b =>
                {
                    b.Property<Guid>("ContinentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContinentID");

                    b.ToTable("Continents");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.World.Nation", b =>
                {
                    b.Property<Guid>("NationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContinentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FlagUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISO3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationID");

                    b.HasIndex("ContinentID");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsCompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.Competition", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.World.Continent", "Continent")
                        .WithMany()
                        .HasForeignKey("ContinentID");

                    b.HasOne("SoccerOpenServer.Models.World.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationID");

                    b.HasOne("SoccerOpenServer.Models.Servers.Server", "Server")
                        .WithMany("Competitions")
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Continent");

                    b.Navigation("Nation");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.CupRound", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Competitions.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.CupTie", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Competitions.CupRound", "CupRound")
                        .WithMany("Ties")
                        .HasForeignKey("CupRoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.Competitions.CupTie", null)
                        .WithMany()
                        .HasForeignKey("NextCupTieID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CupRound");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Contracts.Contract", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithMany("Contracts")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.Teams.Team", "Team")
                        .WithMany("Contracts")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.CoachStats", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithOne("CoachStats")
                        .HasForeignKey("SoccerOpenServer.Models.People.CoachStats", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.ManagerFormationPicked", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithMany("ManagerFormationsPicked")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.ManagerGameStats", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithOne("ManagerGameStats")
                        .HasForeignKey("SoccerOpenServer.Models.People.ManagerGameStats", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.MedicStats", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithOne("MedicStats")
                        .HasForeignKey("SoccerOpenServer.Models.People.MedicStats", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Person", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.World.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoccerOpenServer.Models.Servers.Server", "Server")
                        .WithMany("Persons")
                        .HasForeignKey("ServerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoccerOpenServer.Models.Training.TrainingSchedule", "TrainingSchedule")
                        .WithMany("Persons")
                        .HasForeignKey("TrainingScheduleID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Nation");

                    b.Navigation("Server");

                    b.Navigation("TrainingSchedule");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PersonHealthAndFitness", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithOne("HealthAndFitness")
                        .HasForeignKey("SoccerOpenServer.Models.People.PersonHealthAndFitness", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerCompetitionDiscipline", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Competitions.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerStats", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithOne("PlayerStats")
                        .HasForeignKey("SoccerOpenServer.Models.People.PlayerStats", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedPosition", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", null)
                        .WithMany("PlayerTrainedPositions")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerTrainedRole", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", null)
                        .WithMany("PlayerTrainedRoles")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.PlayerUnavailability", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Competitions.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionID");

                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.PlayerTactic", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithMany("PlayerTactics")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Tactic", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SoccerOpenServer.Models.Teams.Kit", "Kit")
                        .WithOne("Team")
                        .HasForeignKey("SoccerOpenServer.Models.Teams.Team", "KitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.Teams.Stadium", "Stadium")
                        .WithOne("Team")
                        .HasForeignKey("SoccerOpenServer.Models.Teams.Team", "StadiumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Kit");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.TeamTacticPriority", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoccerOpenServer.Models.Teams.Team", "Team")
                        .WithMany("TacticPriorities")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUser", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.People.Person", "Person")
                        .WithOne("AppUser")
                        .HasForeignKey("SoccerOpenServer.Models.Users.AppUser", "PersonID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUserClaim", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany("Claims")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.RefreshToken", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.Users.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.World.Nation", b =>
                {
                    b.HasOne("SoccerOpenServer.Models.World.Continent", "Continent")
                        .WithMany("Nations")
                        .HasForeignKey("ContinentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Continent");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Competitions.CupRound", b =>
                {
                    b.Navigation("Ties");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.People.Person", b =>
                {
                    b.Navigation("AppUser");

                    b.Navigation("CoachStats");

                    b.Navigation("Contracts");

                    b.Navigation("HealthAndFitness");

                    b.Navigation("ManagerFormationsPicked");

                    b.Navigation("ManagerGameStats");

                    b.Navigation("MedicStats");

                    b.Navigation("PlayerStats");

                    b.Navigation("PlayerTactics");

                    b.Navigation("PlayerTrainedPositions");

                    b.Navigation("PlayerTrainedRoles");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Servers.Server", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Kit", b =>
                {
                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Stadium", b =>
                {
                    b.Navigation("Team");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Teams.Team", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("TacticPriorities");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Training.TrainingSchedule", b =>
                {
                    b.Navigation("Persons");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.Users.AppUser", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("SoccerOpenServer.Models.World.Continent", b =>
                {
                    b.Navigation("Nations");
                });
#pragma warning restore 612, 618
        }
    }
}
